#include <lcom/lcf.h>

#define KEYBOARD_IRQ 1
#define INPUT_BUFFER_KEYBOARD 0x64
#define OUTPUT_BUFFER_KEYBOARD 0x60

#define TIMEOUT_ERROR   BIT(6)
#define PARITY_ERROR    BIT(7)
#define OUTPUT_BUFFER_FULL BIT(0)
#define INPUT_BUFFER_FULL  BIT(1)

#define ESC_SCANCODE 0x81